title:            Beelcone
description:      Saumya writes amazing stuff and Lisa fangirls
# disqus_shortname: 
reading_time:     true
words_per_minute: 200
# Your site's domain goes here (eg: https://mmistakes.github.io, http://yourdomain.com, etc)
# When testing locally leave blank or use http://localhost:4000
url: https://beelcone.github.io

# Owner/author information
owner:
  name:           Beelcone
  avatar:         avatar.jpg
  bio:            "Have you ever wanted something so badly that when it's about to happen, you feel this need to sabotage yourself?"
  email:          saumyarastogi15@gmail.com
  # Social networking links used in footer. Update and remove as you like.    
  facebook:        100011628918786
  instagram:      _illumine_

# Background image to be tiled on all pages
background:       bg.jpg

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Australia/Melbourne
future:      true  # publish future dated posts --  true, false (default) 
highlighter: rouge
markdown:    kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-gist
  - jekyll-feed
sass:
  sass_dir: _sass
  style: compressed

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/

# Amount of post to show on home page
paginate: 5

kramdown:
  input: GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

include: 
  - .htaccess
exclude: 
  - "*.less"
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - config
  - gulpfile.js
  - lib
  - log
  - node_modules
  - package.json
  - spec
  - tmp
